# YML是一种文件格式，全称为YAML（YAML Ain't Markup Language），SpringBoot通常使用YML作为项目配置。
# 它是一种人类可读的、简洁明了的数据序列化格式。YAML文件格式通常用于配置文件、数据交换、消息传递和其他应用程序。
# 可以通过文本编辑器进行编辑，也可以通过程序进行解析。YML文件格式是一种以层级缩进的方式表示程序数据结构的格式。
# 在数据表示方面比XML等格式更加简洁清晰易读。YML文件格式通常以“.yml”为扩展名。

# 服务端口
server:
  port: 9171

# Spring配置
spring:
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  # 数据库配置
  datasource:
#    url: jdbc:mysql://124.223.95.146:3306/DB_Music?zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
#    username: root
#    password: f048fac128243533
    url: jdbc:mysql://localhost:3306/DB_Music?zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxWait: 60000
  #Json配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #文件上传相关配置
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

#mybatis 配置
mybatis:
  type-aliases-package: com.shanzhu.music.entity
  mapper-locations: classpath:mapper/*.xml

#是否开启推荐算法
useRecommend: false
